controller_list:
  - name: fake_sim_sys_controller
    joints:
      - wx_agv2_1
      - agv2_virx
      - agv2_viry
      - agv2_virz
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
      - joint_a7